services:
  hazelcast-node-1:
    image: hazelcast/hazelcast:latest
    ports:
      - "5701:5701"
  hazelcast-node-2:
    image: hazelcast/hazelcast:latest
    ports:
      - "5702:5701"
  hazelcast-node-3:
    image: hazelcast/hazelcast:latest
    ports:
      - "5703:5701"
